# Generated by Django 3.2.8 on 2022-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=50, verbose_name='usuario')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('Password', models.CharField(max_length=50, verbose_name='password')),
                ('Direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('Email', models.EmailField(max_length=50, verbose_name='email')),
                ('Telefono', models.CharField(max_length=11, verbose_name='telefono')),
                
               
            ],
        ),
    ]
