# Generated by Django 3.2.8 on 2022-03-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='year_in_school',
        ),
    ]
